# ===============================
# Application Configuration
# ===============================

app.url=https://www.saucedemo.com/

# ===============================
# Browser Configuration
# Supported: chrome, edge, firefox
# ===============================

browser=chrome

# ===============================
# User Credentials
# ===============================

username=standard_user
password=secret_sauce

invalid.username=locked_user123
invalid.password=wrong_password

# ===============================
# Timeouts (Seconds)
# ===============================

implicit.wait=10
explicit.wait=20
page.load.timeout=30

# ===============================
# Window Configuration
# ===============================

maximize.window=true

# ===============================
# Screenshot Folder
# ===============================

screenshot.path=./screenshots/

# ===============================
# Reports Folder
# ===============================

report.path=./reports/

# ===============================
# Execution
# ===============================

headless=false